server.port=${PORT}

# Cofiguración de postgresql
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Cofiguración de jpa
spring.jpa.hibernate.ddl-auto=validate

# Configuración de JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}
app.jwt.issuer=${JWT_ISSUER}
app.jwt.token-prefix=Bearer
app.jwt.header-name=Authorization
