server.port=${PORT:8081}

# Cofiguración de postgresql
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/merklys}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Cofiguración de jpa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
