server.port=${PORT}

# Cofiguración de postgresql
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Cofiguración de jpa
spring.jpa.hibernate.ddl-auto=validate
